### ISSUE TITLE
format should sort object properties

### ISSUE THREAD

**Issue by kalinkrustev** [tapjs/tcompare#4]
Format should sort object properties, otherwise tests can fail when comparing formatted objects with changed order of properties. I am not sure if this issue belongs here or in tap.

**Comment by isaacs** [comment]
Yep!  This landed on 6dba29e14cbf050f260c9f8106956a5c6236bb5c.  Just pass in `{sort: true}` as an option, and it'll do that.

```js
const {format} = require('tcompare')
format(object, { sort: true })
```
