### ISSUE TITLE
Iterable objects fail to match

### ISSUE THREAD

**Issue by kkeri** [tapjs/tcompare#7]
I have a TypeScript class:

```ts
class And {
  rank = null

  constructor (
    public a,
    public b,
  ) { }

  *[Symbol.iterator] (): IterableIterator<Model> {
    yield* And.tree(this.a)
    yield* And.tree(this.b)
  }

  static *tree (model): IterableIterator<Model> {
    if (model instanceof And) yield* model; else yield model
  }
}
```
**Expected behavior**: using the `same` comparison method, two equal instances of the class should match.
**Actual behavior**: two equal instances fail to match.

The cause seems to be that the objects are recognized by **tcompare** as arrays, but the left side object and the right side object are handled differently by the code. In `format.js` I see the following:

```js
  arrayBody() {
    const obj = Array.isArray(this.object)
      ? this.object : Array.from(this.object)
    return obj.map((val, key) =>
      this.arrayEntry(key, val)).join('')
  }
```

Here, the left side object (let's call it `l`) is converted to an array of two elements: `[l.a, l.b]`. The array is iterated over by `map`. The right side object seems to be indexed by the key provided by `map`, but without prior conversion to an array. It doesn't have a `[0]` property, so deeper in the code, `l.a` will be compared against `undefined`.

I wonder what is your advice here. I would be satisfied if only the iterable properties of my class would be compared correctly.

**Comment by isaacs** [comment]
I agree, this is super weird behavior.

Next version will address this.  Wasn't too hard to fix, but did require some deep understanding of the class hierarchy in this module that would've been harder to explain than just do :)
